### ISSUE TITLE
rebuild map using new layers and design

### ISSUE THREAD

**Issue by JackDougherty** [OnTheLine/otl-racial-change-complete-preview#1]
@ilyankou please rebuild this map using new layers and design:

- in Layers folder see new geojson for each year (and a new one for 2018, which requires new tab)
- each geojson starts with a uniform set of six fields (all lower-case): gisjoin, town, area, num, pop, pctwnh (and the latter refers to a new calculation: Percent White non-Hispanic)
- the remaining fields in each layer are non-uniform (with Capitalized names) because the Census varies its racial/ethnic categories over time, and this updated version will display the population of each subgroup of people as the Census labeled them.

I think it's feasible to revise the hover display code to show uniform and non-uniform data for each year as it appears in the geojson layer.

For example, 1910 would display like this:
Canton town
99% White (non-Hispanic)
2,732 population
1,152 Native white - Native parentage
864 Native White Foreign or mixed parentage
684 Foreign-born white
32 Negro
Source: Census report

Also, 2018 would display like this:
Simsbury tract 4661.01
91% White (non-Hispanic)
4,537 population
4,142 White alone (non-Hispanic)
71 Black alone (non-Hispanic)
90 Asian alone (non-Hispanic)
233 Hispanic or Latino
Source: ACS 2014-18 - Social Explorer

Note that we only display % White (non-Hispanic), and no longer display % non-White.

Also, if a data field is null or 0, please omit from hover display.

Let me know if this makes sense, and if yes, please add hours to my bill.

**Comment by ilyankou** [comment]
@JackDougherty Let me know how it looks now, and if you notice any bugs.

* I made info window's font size one pixel smaller because some races (esp the ones in 2010 and 2010) are too long to be nicely displayed.
* I added some spacing so that races are shown in distinct blocks for readability: title, two first lines that don't change, then a mix of races and ethnicity specific to year, and then source
* I also grayed out the text for Source.

Feel free to suggest any CSS changes (spacing, font size, etc).
